### ISSUE TITLE
Help wanted : rxfile

### ISSUE THREAD

**Issue by Wawavoun** [willsowerbutts/gogoboot#12]
Hi,

Not really an issue !

I have a Kiss 68030 and expect to use the rxfile command for transfer binary image from Linux.

Can you add some explanations about this rxfile command ?

What it do, how it works, things to do on the uart other side etc...

Thanks.
Philippe

**Comment by willsowerbutts** [comment]
On the kiss machine, run 'rxfile [filename]'. After pressing enter, DO NOT press any more keys.
On your host machine, use tools/sendrom to send a file. You run: 'tools/sendrom /dev/ttyUSB0 115200 [filename]' - change the UART device name and baud rate to match your system.
The protocol is very simple: 32-bit file size, then the file data.

**Comment by Wawavoun** [comment]
Works well !
Thanks.

**Comment by Wawavoun** [comment]
Hi Will,

I hope you are well.

I am still happy with the Kiss-68030 and the Gogoboot eprom.

I want to do some 68K assembler programming (I have learn that on 6502 /
6809 based 8 bits systems, its my first try on 16/32 bits systems).

For these program I need to call some bios functions(output char, output
string etc...) .

Usually there is an include file with the labels / adresses of each usable
subroutines of the bios. Then this file can be used in any assembler
program that need to call bios functions.

Is there something similar into the source tree of Gogoboot ?
If not what is the best way to find these informations ?

Thanks for your help.
Best regards.
Philippe

Le mer. 11 déc. 2024 à 22:32, Will Sowerbutts ***@***.***> a
écrit :

**Comment by willsowerbutts** [comment]
Hi Philippe
Gogoboot does not supply an interface for programs to use. It is really a bootloader with a focus on the transfer and execution of operating system kernels and other programs which do not require BIOS services. 

However you could flash your machine with [KISS BIOS](https://www.retrobrewcomputers.org/doku.php?id=software:firmwareos:68000:68000) which does provide this (and has had the benefit of much more testing and debugging!)

Will
